### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by Dreamisdead** [oznu/docker-guacamole#1]
Hey.
Can we use LDAP auth with your docker image?
More info: https://guacamole.incubator.apache.org/doc/gug/guacamole-docker.html

**Comment by oznu** [comment]
You can.

Download `guacamole-auth-ldap-0.9.13-incubating.tar.gz` from http://guacamole.incubator.apache.org/releases/0.9.13-incubating/.

Copy just the `guacamole-auth-ldap-0.9.13-incubating.jar` file to `guacamole/extensions/` in your mounted `-v /config` volume.

Then configure the ldap settings in the `guacamole/guacamole.properties` file.

https://guacamole.incubator.apache.org/doc/gug/ldap-auth.html#idm139792316170720

```
ldap-hostname: x
ldap-port: 389
ldap-encryption-method: none
ldap-user-base-dn: x
```

**Comment by Dreamisdead** [comment]
Beautiful. Thanks!
Can you add it to your docker image?
Should be useful for some and doesn't break anything.

**Comment by oznu** [comment]
Sure 😄

**Comment by oznu** [comment]
It looks like enabling the ldap extension without configuring it [does actually break the system](https://github.com/oznu/docker-guacamole/issues/2), I've adjusted the image to allow you to disable/enable auth extensions using an environment variable.

See https://github.com/oznu/docker-guacamole#enabling-extensions

You just have to add `-e EXTENSIONS=auth-ldap` to your run command and LDAP will be activated.

**Comment by Dreamisdead** [comment]
I see. Sorry didn't have time to test yesterday, looks good now tho.

**Comment by jupitern** [comment]
Hi. 
I am trying to setup ldap integration. I have downloaded guacamole-auth-ldap-0.9.13-incubating.jar to extensions dir.
when I login with guacadmin and edit the user the ldap option does not show up. Can you help me?

My properties file looks like this
````
postgresql-hostname: localhost
postgresql-port: 5432
postgresql-database: guacamole_db
postgresql-username: guacamole
postgresql-password: null

# Auth provider class
auth-provider: net.sourceforge.guacamole.net.auth.ldap.LDAPAuthenticationProvider

ldap-hostname: 10.0.32.18
ldap-port: 389
ldap-encryption-method: none
ldap-max-search-results: 1000
ldap-search-bind-dn: adconnection
ldap-search-bind-password: HIDDEN
ldap-user-base-dn: OU=Users,OU=SRVDBT,DC=SRVDBT,DC=local
ldap-username-attribute: sAMAccountName
ldap-user-search-filter: (objectClass=*)

enable-clipboard-integration: true
````

I execute the container with the command
````
docker run --name guacamole -d -p 8080:8080 -v /www/guacamole/root/app:/config -e "EXTENSIONS=auth-ldap" oznu/guacamole
````

**Comment by hansaliyad1** [comment]
@jupitern were able to figure this out?
