### ISSUE TITLE
Problem with postgresql LOG:  database system is shut down /var/run/postgresql:5432 - no response 

### ISSUE THREAD

**Issue by tdslot** [oznu/docker-guacamole#11]
Hi,

When start your image it gives this error.

```LOG:  database system is shut down
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Starting postgres...
FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
LOG:  database system is shut down
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Starting postgres...
FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
LOG:  database system is shut down
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
```

Solution:
Connect to container: `docker exec -it b5e859e762bf /bin/bash`
And run inside container:
`mkdir -p /var/run/postgresql; chown postgres:postgres /var/run/postgresql`

Can you fix it in default image?

**Comment by zenjabba** [comment]
Updated and waiting for rebuild.

**Comment by zenjabba** [comment]
`LOG:  database system is ready to accept connections
/var/run/postgresql:5432 - accepting connections
Starting guacamole client...`

@sippi90

**Comment by mmoser18** [comment]
The first response reads:

> ...
> Solution:
> Connect to container: docker exec -it b5e859e762bf /bin/bash
> And run inside container:
> mkdir -p /var/run/postgresql; chown postgres:postgres /var/run/postgresql
> 

How can one do that if the application always immediately shuts down:
```
...
FATAL:  could not create lock file "/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
LOG:  database system is shut down
```

and the container is then in exit state?
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                     PORTS                                                          NAMES
9203189ec710        kiasaki/alpine-postgres   "/docker-entrypoin..."   3 minutes ago       Exited (1) 3 minutes ago                                                                  awesome_mccarthy
```

How can one apply that chown command to a container that always terminates so quickly that one has no time to enter that command?

**Comment by zenjabba** [comment]
I re-wrote the script to do this for you if you pull the correct docker

**Comment by mmoser18** [comment]
Mind giving me a pointer? Sorry - still relatively new to all this Docker stuff...

**Comment by zenjabba** [comment]
pull from zenjabba/guacamole:0.1

**Comment by mmoser18** [comment]
Sorry - I just realized this is for a completely different image than what I need. I just arrived here googling for the error message that I ran into. You apparently ran into the same issue and fixed that but unfortunately that doesn't help me, because I was using a minimalist postgres image (kiasaki/alpine-postgres). I would need to request that same fix there. Sorry for the bandwidth...

**Comment by rhinot** [comment]
Hi - I'm running into this issue now on the armhf image. Setup is rpi4, omv5, portainer 1.24.1.

Log has the following on repeat:

> /var/run/postgresql:5432 - no response,
> Waiting for postgres to come up...,
> Starting postgres...,
> LOG:  could not translate host name "localhost", service "5432" to address: Temporary failure in name resolution,
> WARNING:  could not create listen socket for "localhost",
> FATAL:  could not create any TCP/IP sockets,
> LOG:  database system is shut down,

What can I get you to debug?

**Comment by zenjabba** [comment]
your server cannot figure out "localhost". You have a DNS problem somewhere

**Comment by rhinot** [comment]
Thanks @zenjabba 

If I run "sudo docker exec guacamole ping localhost" it identifies that localhost is 127.0.0.1 fine and pings fine. Wouldn't that mean my DNS is ok for this container?

**Comment by jorgeg73** [comment]
@rhinot  ever fix your problem. Having the same issue.
Thanks

**Comment by rhinot** [comment]
@jorgeg73 I was using OMV5 and others were having issues with DNS, as @zenjabba guessed, although there was no consistent debug (hence my ping working), nor fix. After banging my head into a wall for a week - trying to reset the DNS of the system, reset docker DNS, manually setting container DNS including both local and remote DNS - I nuked the system and went to straight linux (no OMV). Haven't had this issue since.

**Comment by jorgeg73** [comment]
@rhinot thanks
