### ISSUE TITLE
Can't update database schema when upgrading from 0.9.13 -> 0.9.14

### ISSUE THREAD

**Issue by thestraycat** [oznu/docker-guacamole#13]
Hi there... I've been following guacamole's update instructions and cant seem to update the schema of the postgres database from 0.9.13 to your more recent 0.9.14 using the following command:

  sudo cat /config/guacamole/schema/upgrade/upgrade-pre-0.9.13.sql | psql -d guacamole

is there a user and password i should be specifying? i've tried guacamole and postgres users and -W to prompt for a password... Can you shed some light... It would be super handy to have an upgrade route as i really like the container! 

sudo cat /config/guacamole/schema/upgrade/upgrade-pre-0.9.13.sql | psql -d guacamole -U postgres -W

**Comment by dutran88** [comment]
Database is guacamole_db and user is guacamole
