### ISSUE TITLE
update to Gucamole V1?

### ISSUE THREAD

**Issue by Hobbabobba** [oznu/docker-guacamole#16]
is there any chance to get an update to V1?
`http://guacamole.apache.org/releases/1.0.0/`

**Comment by zenjabba** [comment]
I'm just about done with an upgrade script. I have one final issue I need to fix and I'll post a link for you.

**Comment by zenjabba** [comment]
I've done a pull request but I'm struggling with on final step https://github.com/oznu/docker-guacamole/pull/18

**Comment by oznu** [comment]
Thanks @zenjabba, I'll try and make some time to look at this tomorrow, it's nearly midnight here is Aus.

**Comment by Hobbabobba** [comment]
just saw that the container updated to v1 👍 thx!

**Comment by oznu** [comment]
The `latest` and `1.0.0` tags now provide the latest version of guac. Thanks @zenjabba for doing alot of the work to make this happen.

**Comment by oznu** [comment]
It might be the old versions in the persist folder.

Check `/config/extensions` and remove any old ones. If that works I can make the container clean them up automatically.

**Comment by zenjabba** [comment]
yup, that's the issue. It has both 0.94 and 1.0 version in the folder.

**Comment by oznu** [comment]
Thanks, I'll work out some way to delete any apart from the current versions.

**Comment by zenjabba** [comment]
Already done for you https://github.com/oznu/docker-guacamole/pull/19

**Comment by simonk83** [comment]
Hmm, what am I missing here.   I run this through docker-compose, and I've deleted my existing image and pulled down the new one, but it's still reporting 0.9.14 in the bottom corner...

**Comment by zenjabba** [comment]
@simonk83 what bottom corner? I'm showing 1.0.0 on mine.

**Comment by simonk83** [comment]
Ahhh, never mind, I'm an idiot.   My landing page was caching the old version :D
