### ISSUE TITLE
Change Default URL path

### ISSUE THREAD

**Issue by Pacoboyd** [oznu/docker-guacamole#17]
Unable to reverse proxy due to not being able to change the URL path.

For example by default site is: http://192.168.1.2:8080/

Need the ability to change default url to: http://192.168.1.2:8080/guacamole/

to be able to create a nginx reverse proxy correctly.

**Comment by meme1337** [comment]
> See https://guacamole.apache.org/doc/gug/proxying-guacamole.html#changing-path-with-nginx

I'm having the same issues: the problem I think is that, in the base docker, guacamole runs with /guacamole/ as base url, so it's possible to do a rewrite or w/e via a reverse proxy, but in your version it runs at root, and I wasn't able to do anything without getting a 502 bad gateway by using traefik (kinda new to that though).

I'll see if I can come up with something, problem is that everything is in the Dockerfile, so to have it configurable it should be passed as an arg if I'm not mistaken.

**Comment by Pacoboyd** [comment]
I did manage to get it with this config:

#Guacamole
  location /guacamole/ {
    proxy_pass http://192.168.X.X:5080/;
    proxy_redirect http:// https://;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    access_log off;
  }

But I do agree that it would be nice if it were a passable argument.  Thanks all!

**Comment by meme1337** [comment]
> I did manage to get it with this config:
> 
> #Guacamole
> location /guacamole/ {
> proxy_pass http://192.168.X.X:5080/;
> proxy_redirect http:// https://;
> proxy_buffering off;
> proxy_http_version 1.1;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection $http_connection;
> access_log off;
> }
> 
> But I do agree that it would be nice if it were a passable argument. Thanks all!

I managed to achieve baseurl in oznu/docker-guacamole image by changing the ROOT.war name in the .Dockerfile to the base url i wanted (as well as correctly referencing the folder in the cleanup phase).
But still I didn't manage to proxy it with traefik, so it seems I have to work more on that. 
I've also tried the base image, which exposes the service on /guacamole/ baseurl, but still I had the issue, so your code is the solution if one is using nginx.

**Comment by seegras3** [comment]
I currently have the same problem, if I want to call the page I get the following error message

![Error message](https://puu.sh/D3Sxc/73315eb0e9.jpg)

My nginx-config currently looks like this

´´´
        location /rdp/ {
                proxy_pass http://127.0.0.1:8080/#/;
                proxy_buffering off;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
                proxy_cookie_path /#/ /rdp/;
                access_log off;
        }
´´´

Is there any way to change the path of guacamole?

**Comment by Mbarmem** [comment]
Anyone got this working with Traefik? No matter what i try, i'm getting Error 502.

**Comment by davewthompson** [comment]
https://hub.docker.com/r/davewthompson/guacamole - a version of this which uses the 'guacamole' path rather than root. It may work for you.

**Comment by ansred** [comment]
Is there any builtin openssl package that is pre-installed with any image in Docker?

**Comment by davewthompson** [comment]
@ansred - just use a Nginx proxy in front of the Guacamole instance connected to the same Docker network. Configure SSL in there.

**Comment by ansred** [comment]
@davewthompson that is exactly what I meant, is there a Synology docker image you would recommend and it is easy to deploy? thanks

**Comment by ansred** [comment]
@davewthompson Just found and tested it. it works like a charm.
https://hub.docker.com/r/jlesage/nginx-proxy-manager

Thanks for the tip!

**Comment by eric9876-git** [comment]
> I managed to achieve baseurl in oznu/docker-guacamole image by changing the ROOT.war name in the .Dockerfile to the base url i wanted (as well as correctly referencing the folder in the cleanup phase).

Thanks for this.  I had the same issue and I couldn't get it working, unaltered, with the NGINX config pasted above.  

I looked at other docker images for guacamole and had different problems with all of them.  The official one, with the multiple images, is so complicated.  I think it kind of defeats the whole purpose of simplicity with Docker and it's probably easier to not use Docker if you want to go that route. 
 Other third party images had different issues with them.  The Oznu image is simple and the one that works for me other than this base URL issue.  While I agree, it would be nice if you could: 1) pass an environment variable; 2) have a config file option to set the base url; or 3) if he modified his Dockerfile to bind it to something other than root, the workaround is still relatively simple.   

To automate the change and make it repeatable, I just created a short Dockerfile that takes his image and changes the base URL.  When I start the container, I pull his latest image and then build my Dockerfile over top.  This could also likely be done by modifying his ENTRYPOINT script , "/init", but it would still result in having to build his Dockerfile everytime so I figured this was simpler.

FROM oznu/guacamole:latest

# Move Guacamole Base URL from ROOT to /guacamole/
RUN set -x \
  ### delete old ROOT directory in /usr/local/tomcat/webapps ###
  && rm -rf ${CATALINA_HOME}/webapps/ROOT \ 
  ### rename ROOT.war to guacamole.war (or whatever you want for base url in NGINX) ###
  && mv ${CATALINA_HOME}/webapps/ROOT.war ${CATALINA_HOME}/webapps/guacamole.war
