### ISSUE TITLE
v1.0.0 deletes custom file in /extensions dir

### ISSUE THREAD

**Issue by tscibilia** [oznu/docker-guacamole#23]
According to guacamole [instructions on overriding](http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Branding-the-login-page-td281.html#a1202) the logo and html we are supposed to zip everything together into a .jar file and put it in the GUACAMOLE_HOME/extensions.

I had this working in v0.9.14 of your docker container, but upon upgrading to v1.0.0 it no longer works. It seems to delete the extra file (although I can't confirm, I just know its gone at startup). I've tried stopping the container and copying the file back but it happens every time. 

If I can offer any additional info/details, please let me know how I can help

**Comment by oznu** [comment]
Hi @tscibilia,

This was an bug introduced while trying to ensure older extensions were removed. The latest update should fix this, now the contents of `GUACAMOLE_HOME/extensions` will be removed just **once** after a Guacamole upgrade, rather than after every container restart.

**Comment by tscibilia** [comment]
Thanks, so i can confirm that it doesn't get deleted anymore. Appreciate the fast update and prompt reply!
