### ISSUE TITLE
Duo "Success! Logging you in..." sits there indefinetly 

### ISSUE THREAD

**Issue by Delvien** [oznu/docker-guacamole#25]
When using DUO, I can get the push to my phone, I can approve the push and that proceeds to the "sucess!" message, but it will sit there forever. ( I let it sit there for over an hour) Refreshing, clearing cache, trying another browser, restarting the docker. Nothing works.

**Comment by craigsmooth** [comment]
I'm having the same problem. Has anyone figured this one out yet? Thanks!

**Comment by mjmcphee** [comment]
Same issue here.  I am stumped!

**Comment by haijunsu** [comment]
Same issue when it behinds apache2 proxy server. It works when I use Nginx as proxy server.
Apache2 Virtual Host Configuration:

<VirtualHost *:443>
  ServerName    mydomain.org 
  ServerAdmin admin@mydomin.org
  ProxyPreserveHost On
  <Location /guacamole/>
    Order allow,deny
    Allow from all
    ProxyPass http://192.168.1.19:8080/guacamole/ flushpackets=on
    ProxyPassReverse http://192.168.1.19:8080/guacamole/
  </Location>
  <Location /guacamole/websocket-tunnel>
    Order allow,deny
    Allow from all
    ProxyPass ws://192.168.1.19:8080/guacamole/websocket-tunnel
    ProxyPassReverse ws://192.168.1.19:8080/guacamole/websocket-tunnel
  </Location>
  RequestHeader set X-Forwarded-Proto https
  RequestHeader set X-Forwarded-Port 443
  RequestHeader set X-Forwarded-for "%{REMOTE_ADDR}e"
  RequestHeader set Host "<mydomain.org>"


SSLCertificateFile /etc/letsencrypt/live/<mydomain.org>/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/<mydomain.org>/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

**Comment by prasannacg** [comment]
Hi, I am facing a similar issue. May i know what was the cause for the issue and the fix for it ?
