### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jcoutotelecom** [oznu/docker-guacamole#29]
Hello, first of all thanks for the dockerization, second, is there a way to access this via HTTPS¿?

Regards

**Comment by userhas404d** [comment]
@jcoutotelecom The easiest way HTTPS enable guacamole is with a reverse proxy. LinuxServer.io maintains a solid Nginx based [container](https://hub.docker.com/r/linuxserver/letsencrypt/) with letsencrypt and a ton of common reverse proxy configurations baked in.

**Comment by jcoutotelecom** [comment]
Hello, done with nginx docker, only mapping conf.d and certs(owned certificates) folder.
copy your certificates to /var/lib/docker/volumes/nginx/certs (you can change it but need to change it in the run command)

run this command in your docker machine

docker run -d \
--restart unless-stopped \
-p 443:443 \
-p 80:80 \
-v /var/lib/docker/volumes/nginx/certs:/etc/nginx/certs \
-v /var/lib/docker/volumes/nginx/conf.d:/etc/nginx/conf.d \
--name nginx \
nginx

-------------------------------------------------------

in folder conf.d you should create a file   <domainOrSubdomainName>.conf with this config

server {
    listen              443 ssl;
    server_name         newDomainorSubdomainName.com;
    ssl_certificate      /etc/nginx/certs/NameofTheDomain.com.crt;
    ssl_certificate_key  /etc/nginx/certs/NameOfTheDomain.com.key;  
    
location / {
      proxy_pass http://AdressOfGuacamoleHTTPsite:Port/;
      proxy_buffering off;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
      access_log off;
  }
	}

-------------------------------------------------------------------------

For Redirecting all HTTP to HTTPs petitions, you can create a file in conf.d named for example redirectHTTP.conf with this content

server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}
