### ISSUE TITLE
Drive redirection and printing don't work

### ISSUE THREAD

**Issue by Dreamisdead** [oznu/docker-guacamole#3]
I am testing it now.
Seems like missing libs.
Here's log:
```
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/guacdr-client.so: cannot open shared object file: No such file or directory
guacd[433]: WARNING:	Failed to load guacdr plugin. Drive redirection and printing will not work. Sound MAY not work.
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/guacsnd-client.so: cannot open shared object file: No such file or directory
guacd[433]: WARNING:	Failed to load guacsnd alongside guacdr plugin. Sound will not work. Drive redirection and printing MAY not work.
```
Works on stock guacd docker image.

**Comment by Dreamisdead** [comment]
This seems to 'fix' errors for libs:
mkdir -p /usr/lib/x86_64-linux-gnu/freerdp
ln -s /usr/local/lib/freerdp/guacdr-client.so /usr/lib/x86_64-linux-gnu/freerdp/guacdr-client.so
ln -s /usr/local/lib/freerdp/guacsnd-client.so /usr/lib/x86_64-linux-gnu/freerdp/guacsnd-client.so

After that I can see shared drive, but printing fails .

Ok well, it turns out GhostScript is not installed in container, and after installing it through apt everything works great!

I don't know much about containers yet actually...
Hope you can add all this to your docker image. Cheers. 🙂

**Comment by oznu** [comment]
Thanks for raising this and finding a solution. I'll get this added in the next couple days.

**Comment by prismplex** [comment]
Thank you for the solution @Dreamisdead. 
Similar symlinking has to be done for the :armhf container. This code works for me:
```
mkdir -p /usr/lib/arm-linux-gnueabi/freerdp
ln -s  /usr/local/lib/freerdp/guacdr-client.so /usr/lib/arm-linux-gnueabi/freerdp/guacdr-client.so
ln -s /usr/local/lib/freerdp/guacsnd-client.so /usr/lib/arm-linux-gnueabi/freerdp/guacsnd-client.so
```
