### ISSUE TITLE
Does not see real IP address when using reverse proxy

### ISSUE THREAD

**Issue by iComputer7** [oznu/docker-guacamole#31]
I am using this image behind a NGINX reverse proxy and I have noticed that Guacamole ignores HTTP headers like `X-Real-IP` and `X-Forwarded-For`. Here is my NGINX config:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name [redacted];

    location / {
        proxy_pass http://127.0.0.1:8080/;
        proxy_buffering off;
        access_log off;
        tcp_nodelay on;
        tcp_nopush off;
        sendfile on;
        client_body_buffer_size 10K;
        client_max_body_size 8m;
        client_body_timeout 12;
        keepalive_timeout 15;
        send_timeout 10;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

One thing to note is that the NGINX server is not running in Docker. Port 8080 on the host is mapped to 80 in the container.

**Comment by saintanger** [comment]
I'm passing as well REMOTE_ADDR and  X-Forwarded-For and X-Real-IP via nginx and still I get the nginx ip in the logs, but not the real ip.

Am I missing something here?

**Comment by beechfuzz** [comment]
@saintanger  I'm using this Guacamole container behind [an nginx-proxy container](https://github.com/nginx-proxy/nginx-proxy) and was able to fix this by doing the following (remember this is specific to [this nginx-proxy container](https://github.com/nginx-proxy/nginx-proxy), so you may need to modify this a little to fit your needs):

### 1) In your nginx-proxy container, create a file called /etc/nginx/vhost.d/_\<domain\>_\_location
_Reference: https://guacamole.apache.org/doc/gug/proxying-guacamole.html#proxying-with-nginx_

Example: If the domain is subdomain.domain.com, then create the file `/etc/nginx/vhost.d/subdomain.domain.com_location`

Fill it with the following:

    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    access_log off;

Ultimately, nginx-proxy needs the stuff directly above to be located within the `location` block that is relevant to the domain within its `.conf` file.  With the nginx-proxy container, it will automatically add the contents of `*_location` files into the appropriate `location` blocks in `/conf.d/default.conf`.

### 2) Inside the Guacamole container, modify the `/usr/local/tomcat/conf/server.xml` file

_Reference: https://guacamole.apache.org/doc/gug/proxying-guacamole.html#preparing-servlet-container_

**2a)** Find the `<Connector port="8080" protocol="HTTP/1.1"` entry and add `URIEncoding="UTF-8"` to it.  Mine looks like this:

    <Connector port="8080" protocol="HTTP/1.1"
        connectionTimeout="20000"
        URIEncoding="UTF-8"
        redirectPort="8443" />

**2b)** Find the `<Host>` section and add the following to it:

    <Valve className="org.apache.catalina.valves.RemoteIpValve"
        internalProxies="<IP_Of_Nginx_Proxy>"
        remoteIpHeader="x-forwarded-for"
        remoteIpProxiesHeader="x-forwarded-by"
        protocolHeader="x-forwarded-proto" />

You will need to replace `<IP_Of_Nginx_Proxy>` with the IP of your Nginx-Proxy server.  If your Nginx-Proxy is running in a docker container (like mine), then this will be the internal IP address that is assigned to the container itself, not the IP of the host that is running the container.  For example, my server that is running the docker container (+20 others) has an IP of 192.168.1.100, but Docker assigns the nginx-proxy container its own IP of 172.17.0.10.  I would replace `<IP_Of_Nginx_Proxy>` with `172.17.0.10`.

My entire `<Host>` section looks something like:

    <Host name="localhost"  appBase="webapps"  unpackWARs="true"  autoDeploy="true">

        <...SNIP...>

        <Valve className="org.apache.catalina.valves.RemoteIpValve"
            internalProxies="172.17.0.10"
            remoteIpHeader="x-forwarded-for"
            remoteIpProxiesHeader="x-forwarded-by"
            protocolHeader="x-forwarded-proto" />

    </Host>

### 3) Restart nginx-proxy and Guacamole
