### ISSUE TITLE
Sample config?

### ISSUE THREAD

**Issue by gerroon** [oznu/docker-guacamole#33]
Hi

Is it possible to provide a sample config for "v </path/to/config>:/config "?

**Comment by psychemedia** [comment]
It would also be useful to have a tutorial showing examples of:

1. using a docker-compose file that creates the `docker-guacamole` and example VNC and RDP containers on the same network, along with how to connect to them;
2. separately launched `docker-guacamole`, VNC and RDP containers showing how to connect them.

**Comment by psychemedia** [comment]
I found that no config file is required, just the path. So eg run:

```
mkdir -p guac_config_dir
docker run -p 8080:8080 -v guac_config_dir:/config oznu/guacamole
```

**Comment by gerroon** [comment]
you still need a config file in that folder

**Comment by psychemedia** [comment]
@gerroon Hmmm... I just tried it without one an it worked?

**Comment by m1dm1a** [comment]
I'm also trying to figure out how this is supposed to work.

My instance appears to create files inside the `guac_config_dir` but I am unsure of how to create a config file, and where the application looks for it.

**Comment by gerroon** [comment]
I am not sure even the default user `guacadmin` does not work for me. Also how do I connect the Docker to the local host so I can access the Host pc VNC for instance. 

Maybe someone knows a better maintained Docker for this?

**Comment by m1dm1a** [comment]
After some digging I was able to get this to work.

Upon initial startup i was unable to login with the default credentials until I restarted the container `docker restart CONTAINER_ID`.

Then after looking into it some more I understood what it meant by config. There is no initial configuration FILE required, it is requesting a DIRECTORY on the host system to store the configuration files that will be generated through the web interface.

You are supposed to give it `-v /MYSTORAGE/SUBDIR/STUFF:/config \`. In my config I used `-v /storage/docker/guacamole:/config \` but the path before the colon can be whatever you choose as long as it is a valid storage location that you have access to on the host system.

I hope this helps some people, and if there is someone maintaining this than please mark it solved.

**Comment by gerroon** [comment]
Hi

Thanks for the update. I still cant login with defaults, even after restarting

`Property ldap-user-base-dn is required.`

**Comment by gerroon** [comment]
Btw  I cant seem to be able to change the default password for the default root user :(

**Comment by m1dm1a** [comment]
> Btw I cant seem to be able to change the default password for the default root user :(
Do you mean the root user of the container or of the web app (guacadmin)?

> Hi
> 
> Thanks for the update. I still cant login with defaults, even after restarting
> 
> `Property ldap-user-base-dn is required.`
> 
> The funny thing is that the log says the opposite
> 
> `18:23:18.415 [http-nio-8080-exec-4] INFO o.a.g.r.auth.AuthenticationService - User "guacadmin" successfully authenticated from 192.168.1.100. `
> 
> Edit: nevermind it was the extensions that was causing the issue. I just removed all the extensions from the run line.

Glad to hear that you got it working!

**Comment by gerroon** [comment]
guacadmin

**Comment by m1dm1a** [comment]
> guacadmin

I'm not quite sure how to change the password for that user.

However what I did was create a new admin user, logout, login as the new user, then delete guacadmin.

If you properly passed the configuration directory into the container then you can delete and recreate the container and still access with the new user.

I hope this helps.

**Comment by gerroon** [comment]
@ m1dm1a 

Thanks I appreciate the help.

**Comment by ansred** [comment]
@gerroon that is is a good question.

I had the same issue which was preventing me from using the extensions.


Here is a good sample I got working by running the command using SSH to my DSM

[https://github.com/oznu/docker-guacamole/issues/58](url)


`docker run -p 50:8080 -v /volume1/docker/guacamole/GUACAMOLE_HOME:/config/guacamole -e "EXTENSIONS=auth-ldap,auth-duo" oznu/guacamole`


Hope that helps.
