### ISSUE TITLE
FEATURE: Integrate fail2ban bruteforce protection for logins

### ISSUE THREAD

**Issue by Dreamisdead** [oznu/docker-guacamole#4]
Hey again!
I should say that I have been successfully using your docker image integrated with AD domain through ldap-auth, acting like a remote gateway.

One thing is really bothering tho - nothing is preventing brute force attacks.
Would be nice to integrate something like this: https://www.jimwilbur.com/2016/08/fail2ban_guacamole/

Most of ppl will be running container behind nginx, and we need to tweak filter a bit to not ban host itself, my example: 
`22:26:21.543 [http-apr-8080-exec-6] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.204.xx.xxx, 192.168.0.8] for user "safelogins" failed.`
**192.168.0.8** being reverse proxy and should not be banned.

Can this be implemented? 🙃

**Comment by oznu** [comment]
Do you want to implement fail2ban inside the container or just have it apply the log filter?

**Comment by Dreamisdead** [comment]
Now that you mention it, maybe a good idea is just to expose log files to host. 
So people can install and tweak fail2ban settings for their needs on host.

**Comment by oznu** [comment]
I think so to, to allow the container to modify the system firewall we would need to have the user grant the container extra permissions, `--cap-add=NET_ADMIN`, which is not really ideal.

Perhaps docker already provides all you need to read the container logs with fail2ban? If you run the container with ```--log-driver syslog``` or ```--log-driver journald``` the logs will be directed to the system logs which could then be monitored by fail2ban?

Lots of different logging options here:

https://docs.docker.com/engine/admin/logging/overview/

**Comment by Dreamisdead** [comment]
Thanks, should be no problem using standard docker json logfile. No need to change the container.

**Comment by Doubleho7** [comment]
> Now that you mention it, maybe a good idea is just to expose log files to host.
> So people can install and tweak fail2ban settings for their needs on host.

Did you ever get this working, I'm battling to get this to work with Guacamole using docker. I've got 2fa setup but my site is still vulnerable to brute force with no Fail2Ban.

Please help.
