### ISSUE TITLE
Please add NetBIOS discovery to this

### ISSUE THREAD

**Issue by i00** [oznu/docker-guacamole#42]
To add NetBIOS support for host names I currently need to run:
apt-get install libnss-winbind
apt-get install nano
nano /etc/nsswitch.conf
THEN ADD TO "hosts: XXX" line: "wins" ... eg:
hosts: files dns wins
SAVE
RESTART

... would be great if you had this built into the image so Windows computers could use the hostname rather than the IP or by adding DNS entries to the DNS Server.

**Comment by i00** [comment]
No comment as to why this was closed?

**Comment by ftoledo** [comment]
i looking for this feature too i cannot resolve netbios names

**Comment by i00** [comment]
Not ports ... it works by running what I stated on the docker container

**Comment by ftoledo** [comment]
Is it necessary to configure the wins?

**Comment by i00** [comment]
I don't think it generally is ... not sure ... maybe if you use a domain or have a workgroup name other than the default (workgroup)... I did not need to do anything other than what I stated.

**Comment by i00** [comment]
@oznu ... can you let me know why this was closed please?
Thanks
