### ISSUE TITLE
enable HTTPS?

### ISSUE THREAD

**Issue by Kiuman** [oznu/docker-guacamole#44]
Hei, thanks a lot, I think this container is great!
But what if we want to use https instead of http?

**Comment by grantemsley** [comment]
Most people leave the HTTPS stuff to a proxy like traefik or nginx - that way there's just one place you have to manage the SSL certificates and such.  Traefik can even automatically manage free certs from letsencrypt.

**Comment by ansred** [comment]
@grantemsley do you have a good video tutorial or walk-through KB on the steps needs to be taken to use Traefik or Nginx HTTPS proxy?

Thanks
