### ISSUE TITLE
After successful boot no page loads in web root (FATAL:  role "root" does not exist)

### ISSUE THREAD

**Issue by CHfish-ch** [oznu/docker-guacamole#47]
When I try to get this running on a Synology NAS (currently using full access for everyone (777) on the config directory, see #41 ) 
I see a line "FATAL:  role "root" does not exist" but the Tomcat seems to start. 
But in the end Tomcat loads only an empty page when opening the web root. Any other URI returns an Tomcat error, so it's running
How can I fix the FATAL error?
Thank you!

My log:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.`
`[s6-init] ensuring user provided files have correct perms...exited 0.`
`[fix-attrs.d] applying ownership & permissions fixes...`
`[fix-attrs.d] done.`
`[cont-init.d] executing container initialization scripts...`
`[cont-init.d] 30-defaults.sh: executing...`
`[cont-init.d] 30-defaults.sh: exited 0.`
`[cont-init.d] 40-postgres.sh: executing...`
`The files belonging to this database system will be owned by user "postgres".`
`This user must also own the server process.`

`The database cluster will be initialized with locale "C.UTF-8".`
`The default database encoding has accordingly been set to "UTF8".`
`The default text search configuration will be set to "english".`

`Data page checksums are disabled.`

`fixing permissions on existing directory /config/postgres ... ok`
`creating subdirectories ... ok`
`selecting default max_connections ... 100`
`selecting default shared_buffers ... 128MB`
`selecting dynamic shared memory implementation ... posix`
`creating configuration files ... ok`
`running bootstrap script ... ok`
`performing post-bootstrap initialization ... ok`
`syncing data to disk ... ok`

`WARNING: enabling "trust" authentication for local connections`
`You can change this by editing pg_hba.conf or using the option -A, or`
`--auth-local and --auth-host, the next time you run initdb.`

`Success. You can now start the database server using:`

`    pg_ctl -D /config/postgres -l logfile start`

`[cont-init.d] 40-postgres.sh: exited 0.`
`[cont-init.d] 50-extensions: executing...`
`cat: /config/.database-version: No such file or directory`
`[cont-init.d] 50-extensions: exited 0.`
`[cont-init.d] done.`
`[services.d] starting services`
`Starting guacamole guacd...`
`Starting postgres...`
`[services.d] done.`
`/var/run/postgresql:5432 - no response`
`Waiting for postgres to come up...`
`guacd[269]: INFO:       Guacamole proxy daemon (guacd) version 1.0.0 started`
`guacd[269]: INFO:       Listening on host 127.0.0.1, port 4822`
`LOG:  could not bind IPv6 socket: Cannot assign requested address`
`HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.`
`LOG:  database system was shut down at 2020-01-05 16:02:29 UTC`
`LOG:  MultiXact member wraparound protections are now enabled`
`LOG:  autovacuum launcher started`
`LOG:  database system is ready to accept connections`
`**FATAL:  role "root" does not exist**`
`/var/run/postgresql:5432 - accepting connections`
`CREATE TYPE`
`CREATE TYPE`
`CREATE TYPE`
`CREATE TYPE`
`CREATE TYPE`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE TABLE`
`CREATE TABLE`
`CREATE TABLE`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE INDEX`
`CREATE INDEX`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`CREATE INDEX`
`CREATE INDEX`
`CREATE INDEX`
`CREATE TABLE`
`CREATE INDEX`
`INSERT 0 1`
`INSERT 0 1`
`INSERT 0 6`
`INSERT 0 3`
`Starting guacamole client...`
`05-Jan-2020 16:03:01.687 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.14`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 6 2018 21:13:53 UTC`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.14.0`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.105`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-8u181-b13-2~deb9u1-b13`
`05-Jan-2020 16:03:01.689 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources`
`05-Jan-2020 16:03:01.690 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.19] using APR version [1.5.2].`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].`
`05-Jan-2020 16:03:01.691 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]`
`05-Jan-2020 16:03:01.723 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0j  20 Nov 2018]`
`05-Jan-2020 16:03:01.857 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]`
`05-Jan-2020 16:03:01.913 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]`
`05-Jan-2020 16:03:01.915 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1,041] milliseconds`
`05-Jan-2020 16:03:01.951 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]`
`05-Jan-2020 16:03:01.951 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.14]`
`05-Jan-2020 16:03:02.042 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]`
`05-Jan-2020 16:03:02.607 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [565] ms`
`05-Jan-2020 16:03:02.608 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]`
`05-Jan-2020 16:03:02.624 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [15] ms`
`05-Jan-2020 16:03:02.641 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]`
`05-Jan-2020 16:03:03.002 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [361] ms`
`05-Jan-2020 16:03:03.003 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]`
`05-Jan-2020 16:03:03.043 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [40] ms`
`05-Jan-2020 16:03:03.044 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]`
`05-Jan-2020 16:03:03.078 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [34] ms`
`05-Jan-2020 16:03:03.082 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]`
`05-Jan-2020 16:03:03.088 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]`
`05-Jan-2020 16:03:03.093 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1,177] milliseconds`

**Comment by pinkfloydFR** [comment]
Hi, i have the same problem since i updated my docker :

Starting guacamole client...
/usr/local/tomcat/bin/catalina.sh: line 394: /docker-java-home/jre/bin/java: No such file or directory
FATAL:  role "root" does not exist
/var/run/postgresql:5432 - accepting connections

**Comment by Kenny3231** [comment]
> Hi, i have the same problem since i updated my docker :
> 
> Starting guacamole client...
> /usr/local/tomcat/bin/catalina.sh: line 394: /docker-java-home/jre/bin/java: No such file or directory
> FATAL: role "root" does not exist
> /var/run/postgresql:5432 - accepting connections
Hi,
Same for me, after update my docker again

**Comment by pinkfloydFR** [comment]
Destroyed again, renamed config folder ( for fresh start ), started the docker, waited 3 minutes, and login

success this time :)

**Comment by mondychan** [comment]
Had the container running, had it sit overnight, woke up and this error poped up and wont start again, throwing "FATAL:  role "root" does not exist", any way to fix?

**Comment by ahughes03** [comment]
> > Hi, i have the same problem since i updated my docker :
> > Starting guacamole client...
> > /usr/local/tomcat/bin/catalina.sh: line 394: /docker-java-home/jre/bin/java: No such file or directory
> > FATAL: role "root" does not exist
> > /var/run/postgresql:5432 - accepting connections
> 
> Hi,
> Same for me, after update my docker again

Some error as well.

**Comment by mamema** [comment]
same here

**Comment by ChaosZero112** [comment]
I didn't have a chance to fully look into it, but for those having the "/usr/local/tomcat/bin/catalina.sh: line 394: /docker-java-home/jre/bin/java" error, re-create the container with the ENV wiped.

Fairly certain it's being caused by a change in the `JAVA_HOME` value.

In 0.9.14, it's set as 

JAVA_HOME | /docker-java-home/jre
-- | --

But in 1.1.0, it moved.

JAVA_HOME | /docker-java-home
-- | --

So clearing your ENV values (`EXTENSIONS` can be left) and letting the deployment recreate them should resolve it.

**Comment by mamema** [comment]
in my case, i assume it has something to do with the upgrade to freerdp 2.0, which leads to some issues. The guacamole docu tells me, that the user running guacd needs (now!) a home dir on the machine. As i'm running docker transparent on the host (port 4822 seen by host), i do not understand where such home dir needs to be stored and which user the documentation is talking about.
