### ISSUE TITLE
Urgend: update to Apache Guacamole 1.2.0

### ISSUE THREAD

**Issue by Hobbabobba** [oznu/docker-guacamole#59]
https://guacamole.apache.org/releases/1.2.0/

Can you please update the container to the new version?

Version 1.1.0 has some serious flaws: https://thehackernews.com/2020/07/apache-guacamole-hacking.html

**Comment by MrAvana** [comment]
https://amp.thehackernews.com/thn/2020/07/apache-guacamole-hacking.html

**Comment by MrAvana** [comment]
> https://guacamole.apache.org/releases/1.2.0/
> 
> Can you please update the container to the new version?
> 
> Version 1.1.0 has some serious flaws: https://thehackernews.com/2020/07/apache-guacamole-hacking.html

You can easily build an updated image for yourself with the supplied Dockerfile.

**Comment by Hobbabobba** [comment]
In the dockerfile i changed `GUAC_VER=1.1.0` to `GUAC_VER=1.2.0` and build a new image. 
The container started but just gave me an error, that postgres does not listen.

**Comment by oznu** [comment]
Thanks for reporting this. Done.

**Comment by Minocula** [comment]
No prob....enjoy the donation :D we will check your other cool containers
soon.

Here is something to smile for you:
https://firncloud.trialanderror.tech/s/dPfDqGNtDbfnMfC

Am Fr., 3. Juli 2020 um 14:06 Uhr schrieb oznu <notifications@github.com>:

**Comment by wneiner** [comment]
> Thanks for reporting this. Done.

I am a bit confused. When I do a fresh install of this, the version still comes out to 1.2.0.  What does he mean by done? Do I need to do something specific in order to not get the old version?

I put the oznu/guacamole:latest in the portainer.

Thank you,
