### ISSUE TITLE
postgres" has wrong ownership

### ISSUE THREAD

**Issue by thebetterjort** [oznu/docker-guacamole#6]
OS: Windows 10 ENT
Docker version 17.12.0-ce, build c97c6d6
docker run -p 8085:8080 -v ${PWD}:/config oznu/guacamole

/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
Starting postgres...
FATAL:  data directory "/config/postgres" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.

**Comment by oznu** [comment]
Hi @thebetterjort,

I was not able to replicate this issue, but I've made a small change to enforce the correct permissions on the entire postgres data directory each time the container starts.

Let me know if the latest image solves the problem.

**Comment by xtechgamer735** [comment]
Sadly, this is still a problem.

**Comment by TBhimdi** [comment]
Having the same exact issue. Being able to specify PUID/PGID as environment variables for the docker image would be welcome, it's how other Docker images have solved this problem.
