### ISSUE TITLE
Still installing 1.1.0 on fresh install

### ISSUE THREAD

**Issue by wneiner** [oznu/docker-guacamole#62]
I had responded to a closed ticket about updating to 1.2.0. I figured I would open a new one instead of piggy-backing off of that one.

______________________________________________________________________________

I am a bit confused. When I do a fresh install of this, the version still comes out to 1.1.0, not the 1.2.0 as expected.

What does he mean by 'Done'? Do I need to do something specific in order to not get the old version?

I put the oznu/guacamole:latest in the portainer.

Thank you for your help and sense of urgency,

**Comment by myoriginalusername** [comment]
Same issue here. 

Steps followed: 
* I stopped and removed my old Guacamole container. 
* I then removed the Guacamole image. 
* I then downloaded the new image: `docker pull oznu/guacamole:latest`
* I then used `docker-compose up -d` but when I load the web UI, I can see it's still using 1.1.0

**Comment by wneiner** [comment]
I was thinking about that. I wasn't sure where to find the 'latest' tag and what it referred to. I also tried doing the oznu/guacamole:1.2.0 just for troubleshooting, but that didn't work.

I guess we just need to wait for him to update the tag.

**Comment by wneiner** [comment]
> I was thinking about that. I wasn't sure where to find the 'latest' tag and what it referred to. I also tried doing the oznu/guacamole:1.2.0 just for troubleshooting, but that didn't work.
> 
> I guess we just need to wait for him to update the tag.
> 
> looking at the page with tags, I see the Amd64 one. I will try that.
> 
> oznu/guacamole:1.2.0-amd64

That did it!  Now on 1.2.0, going to see about importing database.

Just need the 'latest' tag updated.

**Comment by ovizii** [comment]
I hit the same problem and looking at docker hub: https://hub.docker.com/r/oznu/guacamole/tags 

I see that the 1.2.0-amd64 tag is way newer than the latest tag. Is this intended? I expected the latest tag to always pull the "latest" version.
