### ISSUE TITLE
Support for NoAuth extension

### ISSUE THREAD

**Issue by ilteoood** [oznu/docker-guacamole#63]
**Describe Your Problem:**
I see that you already support 7 plugins. I would like to see the support for NoAuth extension.

**Logs:**

```
Remove any sensative information.
```

**Screenshots:**

**Environment:**

* **Guacamole Version**: latest docker image
* **Operating System**: Docker on Ubuntu 20.04 LTS

**Comment by oznu** [comment]
Hi @ilteoood,

The NoAuth extension was removed in 1.0.0. See https://issues.apache.org/jira/browse/GUACAMOLE-493
