### ISSUE TITLE
Default credentials won't work

### ISSUE THREAD

**Issue by ckocyigit** [oznu/docker-guacamole#68]
Hey oznu,

thanks for the work!

I've always the same issue when trying to deploy apache guacamole. The creators of the Dockerfile say default credentials are guacadmin and guacadmin but these will never work for me.

Steps to recreate:

pulling the image via my unraid server

running the container with only 2 parameters -p for port and -v for config volume.
Trying default credentials will always end up with this error: 

![grafik](https://user-images.githubusercontent.com/60385015/91639272-a9ab2580-ea15-11ea-9b35-7c022da6d6ad.png)

Thanks!

**Comment by MisterBaz** [comment]
Sorry to say, the developer never actually responds to any of these posts.
I can say for sure, that the default creds are indeed guacadmin/guacadmin from using the latest docker image as of August 31 2020.
You may need to check your guacamole logs to see if something went wrong during your install, or if you have persistent volumes that might have a changed password.
