### ISSUE TITLE
How do you restart the container/exit the shell

### ISSUE THREAD

**Issue by billyblue52** [oznu/docker-guacamole#7]
Hi,

I have two questions about this image hopefully you can help please.

1)  How do you exit the shell without shutting down the container? 

2) How do you safely stop and relaunch the container eg: after a reboot

**Comment by oznu** [comment]
Use `--restart=always` and `-d`.

`-d` runs the container as a background process. `--restart=always` will restart the container automatically after a reboot (or if it crashes) until manually stopped or destroyed.

```
docker run --restart=always -d oznu/unms
```
