### ISSUE TITLE
Clipboard Copy causes RDP session to disconnect

### ISSUE THREAD

**Issue by monalisa-overdrive** [oznu/docker-guacamole#73]
**Describe The Bug:**

I am running xRDP on CentOS and connecting via RDP on Guacamole  
While connected to an RDP session, highlighting text then > CTRL+C or RightClick>Copy disconnects the session giving a Connection Error

**To Reproduce:**

1. Connect to an RDP session
2. highlight any text
3. try to copy the text (either by Ctrl+C or Right Click > copy)

**Expected behavior:**

text should copy without error

**Logs:**

```
guacd[263]: INFO:Connection "$50194d03-eb7b-4365-87b9-4dbdaf7397f0" removed.
guacd[263]: INFO:Creating new client for protocol "rdp"
guacd[263]: INFO:Connection ID is "$2f526a34-45b5-4e53-a7ab-11c3650bf8a8"
guacd[1594]: INFO:Security mode: Negotiate (ANY)
guacd[1594]: INFO:Resize method: display-update
guacd[1594]: INFO:User "@8688a189-d2b7-4a93-8a54-983e5fc42a50" joined connection "$2f526a34-45b5-4e53-a7ab-11c3650bf8a8" (1 users now present)
18:24:56.233 [http-nio-8080-exec-2] INFO  o.a.g.tunnel.TunnelRequestService - User "<user>" connected to connection "1".
guacd[1594]: INFO:Loading keymap "base"
guacd[1594]: INFO:Loading keymap "en-us-qwerty"
guacd[1594]: INFO:Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[1594]: INFO:Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[1594]: INFO:Connected to RDPDR 1.12 as client 0x26d82ae0
guacd[1594]: INFO:RDPDR user logged on
guacd[1594]: ERROR:Connection closed.
guacd[1594]: INFO:Internal RDP client disconnected
guacd[1594]: INFO:User "@8688a189-d2b7-4a93-8a54-983e5fc42a50" disconnected (0 users remain)
guacd[1594]: INFO:Last user of connection "$2f526a34-45b5-4e53-a7ab-11c3650bf8a8" disconnected
guacd[263]: INFO:Connection "$2f526a34-45b5-4e53-a7ab-11c3650bf8a8" removed.
18:25:30.926 [Thread-56] INFO  o.a.g.tunnel.TunnelRequestService - User "<user>" disconnected from connection "1". Duration: 34693 milliseconds
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/22268708/94745481-c99d7400-0348-11eb-88d5-4e971ce10bf2.png)

**Environment:**

* **Guacamole Version**:  oznu/docker-guacamole:latest
* **Operating System**:  docker

**Comment by monalisa-overdrive** [comment]
this is still an issue

**Comment by raman777** [comment]
Same issue here. After pressing Ctrl.-C or issue any(!) copy action (via Ctrl-Ins oder via menu of an abitrary application) the session crashes. We are using Guacamole 1.2.0 currently.

BTW: May there be an issue with FreeRDP 2.0.0-rc3/4 which may cause this?  --> https://github.com/FreeRDP/FreeRDP/issues/5686
