### ISSUE TITLE
1.1.0 to 1.2.0 upgrade

### ISSUE THREAD

**Issue by MRIIOT** [oznu/docker-guacamole#74]
Hello.  Does anyone have upgrade notes from 1.1.0 to 1.2.0?

**Comment by RedSparr0w** [comment]
If you are meaning for this repo:
https://github.com/oznu/docker-guacamole/compare/1.1.0...oznu:1.2.0

Otherwise for Guacamole:
https://guacamole.apache.org/releases/1.2.0/#release-notes
